### ISSUE TITLE
Testing.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#14]
**Issue:** 

**Undertake code validation and testing.**

**Tasks:**
- [x] Delete commented out code.
- [x] Comment out console.log (err)s.
- [x] Create TESTING.md.
- [x] Complete **TESTING Checklist** issue.
