### ISSUE TITLE
User sign out securely.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#20]
**EPIC:** Authentication.

**As a user, I would like to sign out so that I know my session has been closed securely.**

**Acceptance Criteria (AC)**

- [x] AC-1: Display sign out icon in nav bar.

- [x] AC-2: On sign out, nav bar will display sign-in and sign-up icons.

**Tasks**

- [x] Task 1: Create Navbar.

- [x] Task 2: Add sign-in and sign-out functionality.
