### ISSUE TITLE
Nav bar on each page.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#21]
**EPIC:** Navigation.

**As a user, I would like to view a navbar from every page so that I can navigate seamlessly between pages.**

**Acceptance Criteria (AC)**

- [x] AC-1: A functional nav bar will be displayed on each page with seamless links to other pages.

- [x] AC-2: Additional nav bar links for signed-in users.

**Tasks**

- [x] Task 1: Create nav bar with React Bootstrap.

- [x] Task 2: Add Font Awesome icons.

- [x] Task 3: Create links to connect pages with additional links for signed-in users.

- [x] Task 4: Test functionality.
