### ISSUE TITLE
Create a post.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#23]
**EPIC:** Add and like posts.

**As a logged-in user, I would like to create a post to share on the platform so that I can engage with other users.**

**Acceptance Criteria (AC)**

- [x] AC-1: A user can upload an image.

- [x] AC-2: A user can add information about an image eg. title, artist, location and borough.

**Tasks**

- [x] Task 1: Create Post.js

- [x] Task 2: Create PostPage.js

- [x] Task 3: Test functionality.
