### ISSUE TITLE
Edit or delete a post.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#24]
**EPIC:** Add and like posts.

**As a logged-in user, I would like to edit or delete my posts so that I can update or delete them after their creation.**

**Acceptance Criteria (AC)**

- [x] AC-1: User can edit and save changes to a post.

- [x] AC-2: User can delete a post.

**Tasks**

- [x] Task 1: Create PostEditForm.js

- [x] Task 2: Create style sheets.

- [x] Task 3: Test functionality.
