### ISSUE TITLE
Like or unlike a post.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#25]
**EPIC:** Add and like posts.

**As a logged-in user, I would like to like/unlike a post so that I can show my appreciation of the content.**

**Acceptance Criteria (AC)**

- [x] AC-1: A like icon is displayed for each post which can be clicked to like and unlike.
- [x] AC-2: The number of likes for each post is displayed.

**Tasks**

- [x] Task 1: Add handleLike() and handleUnLike() functions to post.js
- [x] Task 2: Add css styling .
- [x] Task 3: Test functionality.
