### ISSUE TITLE
User can view all posts they have liked.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#26]
**EPIC:** Add and like posts.

**As a logged-in user, I would like to view all posts I have liked so that I can scroll through my favourite content.**

**Acceptance Criteria (AC)**

- [x] AC-1: A 'liked' page will display all posts liked by a particular user.

- [x] AC-2: The user can scroll through the posts without interruption.

**Tasks**

- [x] Task 1: Create 'Liked' link in NavBar.js.
- [x] Task 2: Set up route in App.js to render profiles user has liked.
- [x] Task 3: Add css styling.
- [x] Task 4: Test functionality.
