### ISSUE TITLE
User can scroll through posts on any given page.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#27]
**EPIC:** View posts.

**As a user, I would like to scroll continuously through the posts on any given page so that I can view them without interruption.**

**Acceptance Criteria (AC)**

- [x] AC-1: Posts are displayed on each page in descending order of date created.

- [x] AC-2: User can scroll through posts seamlessly.

**Tasks**

- [x] Task 1: Add React Infinite Scroll to PostsPage.js.
- [x] Task 2: Test functionality.
