### ISSUE TITLE
Search posts with keywords.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#29]
**EPIC:** View posts.

**As a user, I would like to search posts with keywords so that I can find posts and user profiles that most interest me.**

**Acceptance Criteria (AC)**

- [x] AC-1: A search bar is displayed at the top of the posts page.
- [x] AC-2: A user can enter a key word relevant to them and posts or profiles containing this will be displayed.

**Tasks**

- [x] Task 1: Set up search fields in API.
- [x] Task 2: Add search function to PostsPage.js.
- [x] Task 3: Add css styling.
- [x] Task 4: Test functionality.
