### ISSUE TITLE
View details of a single post.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#30]
**EPIC:** View posts.

**As a user, I would like to view the details of a single post so that I can learn more about it.**

**Acceptance Criteria (AC)**

- [x] AC-1: When a user clicks on a post in the post list a more detailed view of the post will be displayed.

**Tasks**

- [x] Task 1: Create PostPage.js.
- [ ] Task 2: Add css styling.
- [ ] Task 3: Test functionality.
