### ISSUE TITLE
User can view posts filtered by users they follow.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#31]
**EPIC:** View posts.

**As a logged-in user, I would like to view posts filtered by users I follow so that I can keep up-to-date with their content.**

**Acceptance Criteria (AC)**

- [x] User will be able to access a 'Feed' page which displays posts by users they follow.

**Tasks**

- [x] Task 1: Create 'Feed' link in NavBar.js.
- [x] Task 2: Set up route in App.js to render profiles user is following.
- [x] Task 3: Add css styling.
- [x] Task 4: Test functionality.
