### ISSUE TITLE
View a user's profile.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#32]
**EPIC:** Profiles.

**As a user, I would like to view other users’ profiles so that I can see their posts and learn more about them.**

**Acceptance Criteria (AC)**

- [x] Display profile with photo, bio and activity data.

**Tasks**

- [x] Task 1: Create Profile.js and ProfilePage.js.
- [x] Task 2: Add css styling.
- [x] Task 3: Test functionality.
