### ISSUE TITLE
View a list of the most followed profiles.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#33]
**EPIC:** Profiles.

**As a user, I would like to view a list of the most followed profiles so that I can see which are the most popular.**

**Acceptance Criteria (AC)**

- [x] AC-1: Users can view a panel ranking users by popularity.
- [x] AC-2: For small screens, panel will display horizontally below nav bar.
- [x] AC-3: For larger screens, panel will display vertically to right of posts.

**Tasks**

- [x] Task 1: Create ProfileDataContext.js.
- [x] Task 2: Import profileData to PopularProfiles.js.
- [x] Task 3: Add css styling.
- [x] Task 4: Test functionality.
