### ISSUE TITLE
View all published posts by a specific user.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#34]
**EPIC:** Profiles.

**As a user, I would like to see all the published posts by a specific user so that I can review their post history.**

**Acceptance Criteria (AC)**

- [x] Clicking on a profile avatar will display all posts by that user.

**Tasks**

- [x] Task 1: Create ProfilePage.js.
- [x] Task 2: Add css styling.
- [x] Task 3: Test functionality.
