### ISSUE TITLE
User can follow/unfollow another user.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#35]
**EPIC:** Profiles.

**As a logged-in user, I would like to follow/unfollow other users so that I can see and remove posts by specific users in my post feed.**

**Acceptance Criteria (AC)**

- [x] AC-1: User can click on follow/unfollow buttons to make their choice.
- [x] AC-2: Followed status is displayed for most popular users.

**Tasks**
- [ ] Task 1: Create Profile.js.
- [ ] Task 2: Add handleFollow and handleUnfollow functions.
- [ ] Task 3: Add css styling.
- [ ] Task 4: Test functionality.
