### ISSUE TITLE
A user can edit their profile.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#36]
**EPIC:** Profiles.

**As a logged-in user, I would like to edit my profile so that I can keep my details up to date.**

**Acceptance Criteria (AC)**

- [x] User can edit their profile details.

**Tasks**

- [x] Task 1: Create ProfileEditForm.js.
- [x] Task 2: Add css styling.
- [x] Task 3: Test functionality.
