### ISSUE TITLE
A user can update username/password on their profile page.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#37]
**EPIC:** Profiles.

**As a logged-in user, I would like to update my username/password so that I can make changes and keep my account secure.**

**Acceptance Criteria (AC)**

- [ ] AC-1: User can access menu with options to edit their username/password.
- [ ] AC-2: User can save changes or cancel their action/s.

**Tasks**

- [ ] Task 1: Create UsernameForm.js.
- [ ] Task 2: Create UserPaswordForm.js.
- [ ] Task 3: Add css styling.
- [ ] Task 4: Update functionality.
