### ISSUE TITLE
Activity stats on a specific user's profile.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#38]
**EPIC:** Profiles.

**As a user, I would like to see stats on a specific user’s profile so I can know how many posts they have made, followers they have, and how many users they are following.**

**Acceptance Criteria (AC)**

- [x] Display number of posts, followers and following on a user's profile.

**Tasks**

- [x] Task 1: Import post and follower/following counts to ProfilePage.js.
- [x] Task 2: Add css styling.
- [x] Task 3: Test functionality.
