### ISSUE TITLE
View user comments.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#39]
**EPIC:** Comments.

**As a user, I would like to view comments by other users so that I can know what they think about posts.**

**Acceptance Criteria (AC)**

- [x] AC-1: Comments will be displayed below each post.
- [x] AC-2: Users can scroll through the comments list seamlessly.

**Tasks**

- [x] Task 1: Import comment components to PostPage.js.
- [x] Task 2: Add css styling.
- [x] Task 3: Test functionality.
