### ISSUE TITLE
Display how old a comment is.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#40]
**EPIC:** Comments.

**As a user, I would like to see how long ago a comment was made so that I can know how old it is.**

**Acceptance Criteria (AC)**

- [x] Display how long ago a comment was made above the comment.

**Tasks**

- [x] Task 1: Set up 'naturaltime' function in API.
- [x] Task 2: Import comment components to PostPage.js.
- [x] Task 3: Add css styling.
- [ ] Task 4: Test functionality.
