### ISSUE TITLE
Comment on a post.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#41]
**EPIC:** Comments.

**As a logged-in user, I would like to comment on a post so that I can share my thoughts about its content.**

**Acceptance Criteria (AC)**

- [x] AC-1: A user can click on a comments icon to make a comment.
- [x] AC-2: Comments will be displayed below the post.

**Tasks**

- [x] Task 1: Create Comment.js and CommentCreateForm.js.
- [x] Task 2: Add css styling.
- [x] Task 3: Test functionality.
