### ISSUE TITLE
Edit a comment.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#42]
**EPIC:** Comments.

**As a logged-in user, I would like to edit any comment I have made so that I can update its content.**

**Acceptance Criteria (AC)**

- [x] AC-1: A logged-in user can update their existing comment.

**Tasks**

- [x] Task 1: Create CommentEditForm.js.
- [x] Task 2: Add css styling.
- [x] Task 3: Test functionality.
