### ISSUE TITLE
Delete a comment.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#43]
**EPIC:** Comments.

**As a logged-in user, I would like to delete any comment I have made so that I can remove it from the site.**

**Acceptance Criteria (AC)**

- [x] A logged-in user can delete a comment they have made.

**Tasks**

- [x] Task 1: Create Comment.js.
- [x] Task 2: Add handleDelete() function.
- [x] Task 3: Add css styling.
- [x] Task 4: Test functionality.
