### ISSUE TITLE
Administrator can create an Online Talk event.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#44]
**EPIC:** Online talk events.

**As an administrator, I would like to create an Online Talk event so that I can publish it on the talks page.**

**Acceptance Criteria (AC)**

- [x] AC-1: Administrator can log in to Django Admin panel.

- [x] AC-2: Administrator can populate fields for an Online Talk event and save.

**Tasks**

- [x] Task 1: See sculpture-drf-api repo for set up of API and Talk model in Django.

- [x] Task 2: Test functionality.
