### ISSUE TITLE
Administrator can edit and delete an Online Talk event.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#45]
**EPIC:** Online talk events.

**As an administrator, I would like to edit and delete an Online Talk event so that I can amend details and remove the event if necessary.**

**Acceptance Criteria (AC)**

- [x] AC-1: Administrator can view online talk events in the Django Admin panel.

- [x] AC-2: Administrator can make changes to events or delete them and these changes will be displayed at the front-end.

**Tasks**

- [x] Task 1: See sculpture-drf-api repo for set up of API and Talk model in Django.

- [x] Task 2: Test functionality.
