### ISSUE TITLE
User can book an Online Talk event.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#48]
**EPIC:** Online talk events.

**As a logged-in user, I would like to submit a booking for an Online Talk event so that I can attend and engage with other users.**

**Acceptance Criteria (AC)**

- [x] AC-1: User can view list of talks.

- [x] AC-2: User can book an event and add their questions and suggestions.

- [x] AC-3: User can view the bookings they have made.

**Tasks**

- [x] Task 1: Create booking.js

- [x] Task 2: Create BookingCreateForm.js

- [x] Task 3: Create Bookings.js

- [x] Task 4: Add css styling.

- [ ] Test functionality.
