### ISSUE TITLE
User can edit and delete bookings for Online Talk events.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#49]
**EPIC:** Online talk events.

**As a logged-in user, I would like to view, edit and delete my bookings for Online Talk events so that I can check and change my bookings if necessary.**

**Acceptance Criteria (AC)**

- [x] AC-1: User can see a list of their booked talk events.

- [x] AC-2: User can edit or delete their events and an updated list of their bookings will be displayed.

**Tasks**

- [x] Task 1: Create BookingEditForm.js

- [x] Task 2: Add css styling.

- [x] Task 3: Test functionality.
