### ISSUE TITLE
Site administration access.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#50]
**EPIC:** Site administration.

**As an administrator, I would like to access the administrator panel so that I can monitor and delete posts, comments and users if necessary.**

**Acceptance Criteria (AC)**

- [x] AC-1: Administrator will be able to log in to the administrator panel.
- [x] AC-2: Administrator will be able to perform site administration functions.

**Tasks**

- [x] Task 1: Create Django rest API for project.

- [x] Task 2: Create superuser.

- [x] Task 3: Test admin functionality.
