### ISSUE TITLE
Sign-in and Sign-up options.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#51]
**EPIC:** Navigation.

**As a signed-out user, I would like to see sign-in and sign-up options so that I can sign in/sign up.**

**Acceptance Criteria (AC)**

- [x] AC-1: Sign-in and Sign-up icons will be displayed.

- [x] AC-2: Clicking on Sign-up will redirect the user to a sign-up form.

- [x] AC-2: Clicking on Sign-in will redirect the user to a sign-in form.

**Tasks**

- [x] Task 1: Create NavBar.

- [x] Task 2: Add Sign-up and Sign-in icons with paths to the relevant forms.

- [x] Task 3: Test functionality.
