### ISSUE TITLE
Set up project repos and workspaces.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/london-outdoor-sculpture#7]
**Issue:**
Set up repo and workspace for API and front-end project.

**Tasks**
- [x] Create Django Rest Framework (API) repo in Github and workspace in Gitpod.
- [x] Create React workspace repo in Github and workspace in Gitpod.
- [x] Confirm library versions / dependencies.
- [x] Test initial deployment to Heroku.
